### ISSUE TITLE
Create bomb planting script for objectives

### ISSUE THREAD

**Issue by JessevGool** [JessevGool/Global_Mobilization_Event#25]
The objectives in TBA will be ammo/fuel trucks that will be invincible to regular damage.
To destroy these objectives players will need to interact with the vehicle and plant a bomb on it.
This bomb will start a countdown in which defenders will have time to defuse the bomb.

If the bomb is defused attackers should be able to restart the process.
If the bomb isn't defused the vehicle should explode and a trigger marking objective completed should be triggered

**Comment by tanaaKa** [comment]
Added in https://github.com/JessevGool/Global_Mobilization_Event/pull/32
