### ISSUE TITLE
Test objective logics in MP

### ISSUE THREAD

**Issue by JessevGool** [JessevGool/Global_Mobilization_Event#35]
Objective logic needs to be tested on the server. Could run into locality issues

**Comment by phoenixoverlord** [comment]
Objectives will complete and will cycle to next sector. Main Objectives however keep reappearing (task) and then auto completing instantly, rinse and repeat every 5 mins or so

**Comment by JessevGool** [comment]
@tanaaKa would be helpful if you took a look at the mission file,
none of the triggers that create the tasks are repeatable so I don't know why this is happening

**Comment by tanaaKa** [comment]
Checking into now

**Comment by tanaaKa** [comment]
Created https://github.com/JessevGool/Global_Mobilization_Event/tree/locality_test for testing. Uses hints every time a trigger fires for tracking.
